name = "spades_ui"
version = "1.0.0"

target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
lustre = "~> 3.1"
lustre_ui = "~> 0.3"
lustre_http = "~> 0.5"
esgleam = "~> 0.6"

[dev-dependencies]
gleeunit = "~> 1.0"
