name = "spades_ui"
version = "1.0.0"

target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.53.0 and < 1.0.0"
lustre = ">= 4.6.3 and < 5.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
lustre_websocket = ">= 0.7.6 and < 1.0.0"
modem = ">= 2.0.1 and < 3.0.0"
lustre_ui = ">= 0.4.0 and < 1.0.0"
rsvp = ">= 1.0.1 and < 2.0.0"
gleam_fetch = ">= 1.1.0 and < 2.0.0"
gleam_javascript = ">= 0.13.0 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
lustre_dev_tools = ">= 1.6.5 and < 2.0.0"
