version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_NAME: spades_dev
      DB_USER: spades
      DB_PASS: spades
      DB_HOST: db
    volumes:
      - /opt/app/build
      - /opt/app/assets/node_modules
      - ./:/opt/app
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: spades
      POSTGRES_PASSWORD: spades
      POSTGRES_DB: spades_dev
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
