version: '3'
services:
  ui:
    build:
      context: ./client
    volumes:
      - ./client:/opt/app
      - /opt/app/build
    ports:
      - "8000:8000"
    depends_on:
      - api

  api:
    tty: true
    build:
      context: ./server
    environment:
      DB_NAME: spades_dev
      DB_USER: spades
      DB_PASS: spades
      DB_HOST: db
      PASSWORD_SALT: 1234
      TERM: "xterm-256color"
    volumes:
      - ./server:/opt/app
      - /opt/app/build
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: spades
      POSTGRES_PASSWORD: spades
      POSTGRES_DB: spades_dev
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
