version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /opt/app/deps
      - /opt/app/_build
      - /opt/app/assets/node_modules
      - ./:/opt/app
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: spades
      POSTGRES_PASSWORD: spades
      POSTGRES_DB: spades_dev
    volumes:
      - /var/lib/postgresql/data
