services:
  ui:
    build:
      context: ./client
    volumes:
      - client_build:/opt/app/build
      - node_modules:/opt/app/node_modules
      - ./client:/opt/app
    ports:
      - "5000:5000"
    depends_on:
      - api

  api:
    tty: true
    build:
      context: ./server
    environment:
      PGDATABASE: spades_dev
      PGUSER: spades
      PGPASS: spades
      PGHOST: db
      PASSWORD_SALT: 1234
      TERM: "xterm-256color"
    volumes:
      - server_build:/opt/app/build
      - ./server:/opt/app
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: spades
      POSTGRES_PASSWORD: spades
      POSTGRES_DB: spades_dev
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
volumes:
  client_build:
  server_build:
  node_modules:
