name = "spades"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["Apache-2.0"]
description = "A Gleam library..."
repository = { type = "github", user = "rawhat", repo = "spades" }
links = [{ title = "Website", href = "https://spades.rawhat.net" }]

[dependencies]
gleam_stdlib = "~> 0.28"
gleam_http = "~> 3.2"
gleam_erlang = "~> 0.18"
mist = "~> 0.10"
gleam_pgo = "~> 0.4"
gleam_json = "~> 0.5"
gleam_crypto = "~> 0.3"

[dev-dependencies]
gleeunit = "~> 0.10"
