name = "spades"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["Apache-2.0"]
description = "A Gleam library..."
repository = { type = "github", user = "rawhat", repo = "spades" }
links = [{ title = "Website", href = "https://spades.rawhat.net" }]
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.33"
gleam_http = "~> 3.5"
gleam_erlang = "~> 0.23"
# mist = "~> 0.12"
mist = "~> 0.15"
gleam_pgo = "~> 0.6"
gleam_json = "~> 0.7"
gleam_crypto = "~> 0.5"
gleam_otp = "~> 0.8"

[dev-dependencies]
gleeunit = "~> 1.0"
