name = "spades"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["Apache-2.0"]
description = "A Gleam library..."
repository = { type = "github", user = "rawhat", repo = "spades" }
links = [{ title = "Website", href = "https://spades.rawhat.net" }]
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = ">= 0.38.0 and < 1.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_pgo = ">= 0.10.0 and < 1.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
logging = ">= 1.2.0 and < 2.0.0"
mist = ">= 1.2.0 and < 2.0.0"
decode = ">= 0.1.0 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
