name = "spades"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["Apache-2.0"]
description = "A Gleam library..."
repository = { type = "github", user = "rawhat", repo = "spades" }
links = [{ title = "Website", href = "https://spades.rawhat.net" }]
gleam = ">= 1.7.0"

[dependencies]
gleam_stdlib = ">= 0.53.0 and < 1.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
gleam_crypto = ">= 1.4.0 and < 2.0.0"
gleam_otp = ">= 0.16.1 and < 1.0.0"
logging = ">= 1.3.0 and < 2.0.0"
mist = { path = "/home/alex/gleams/mist" }
envoy = ">= 1.0.2 and < 2.0.0"
pog = ">= 3.2.0 and < 4.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
squirrel = ">= 3.0.0 and < 4.0.0"
gleam_time = "1.0.0-rc1"
lustre = ">= 4.6.3 and < 5.0.0"
shared = { path = "../shared" }

[dev-dependencies]
startest = ">= 0.4.0 and < 1.0.0"
